[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "parareal"
version = "0.0.1"
description = "Parareal algorithm"
readme = "README.md"


[[project.authors]]
name = ""
email = ""

name = ""
email = ""
[project]
authors = [
  {name = "Oussama BOUHENNICHE", email = "Oussamabouhenniche14@gmail.com"},
  {name = "Narimane ZAOUACHE", email = ""},

]

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"

[tool.setuptools]
packages = ["parareal", "parareal.lorenz, "parareal.parareal", "parareal.plot", "parareal.solver"]