name: Python package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libmpich-dev \
          python3-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test with pytest
      run: |
        pytest
    - name: Run MPI tests
      run: |
        mpiexec -n 2 pytest tests/test_mpi_parareal.py
