name: Python package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libmpich-dev \
          python3-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run standard tests
      run: |
        pytest

    - name: Run MPI tests with Python ${{ matrix.python-version }}
      run: |
        echo "Running MPI tests with Python ${{ matrix.python-version }}"
        mpiexec -n 2 python -m pytest tests/test_mpi_parareal.py
      env:
        MPIEXEC_TIMEOUT: 100

    - name: Generate coverage report
      run: |
        pytest --cov=parareal --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
